def raise_exception(request):
    raise AssertionError('historylinks test')
